# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Doctor/Doctor.API/Doctor.API.csproj", "Doctor/Doctor.API/"]
COPY ["BuildingBlocks/BuildingBlocks.Messaging/BuildingBlocks.Messaging.csproj", "BuildingBlocks/BuildingBlocks.Messaging/"]
COPY ["BuildingBlocks/BuildingBlocks/BuildingBlocks.csproj", "BuildingBlocks/BuildingBlocks/"]
COPY ["Doctor/Doctor.Application/Doctor.Application.csproj", "Doctor/Doctor.Application/"]
COPY ["Doctor/Doctor.Domain/Doctor.Domain.csproj", "Doctor/Doctor.Domain/"]
COPY ["Doctor/Doctor.Infrastructure/Doctor.Infrastructure.csproj", "Doctor/Doctor.Infrastructure/"]
RUN dotnet restore "./Doctor/Doctor.API/Doctor.API.csproj"
COPY . .
WORKDIR "/src/Doctor/Doctor.API"
RUN dotnet build "./Doctor.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Doctor.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Doctor.API.dll"]