# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'brain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62rain.proto\x12\x05\x62rain\"\"\n\x11TumorImageRequest\x12\r\n\x05image\x18\x01 \x01(\t\"A\n\x17TumorPredictionResponse\x12\x12\n\ntumor_type\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x32Y\n\x12\x42rainTumorAnalyzer\x12\x43\n\x07Predict\x12\x18.brain.TumorImageRequest\x1a\x1e.brain.TumorPredictionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TUMORIMAGEREQUEST']._serialized_start=22
  _globals['_TUMORIMAGEREQUEST']._serialized_end=56
  _globals['_TUMORPREDICTIONRESPONSE']._serialized_start=58
  _globals['_TUMORPREDICTIONRESPONSE']._serialized_end=123
  _globals['_BRAINTUMORANALYZER']._serialized_start=125
  _globals['_BRAINTUMORANALYZER']._serialized_end=214
# @@protoc_insertion_point(module_scope)
